#!/usr/bin/env python3
"""
Build dist/edges.json from data/data.json + data/entities.json.

Algorithm (locked by eng review):
  1. Read events (with `entities: [...]`) and entity registry.
  2. Skip any entity with `quarantined: true` — don't emit edges through it
     (OV-7 guard: new LLM-proposed entities sit in quarantine until ≥2
     distinct events mention them).
  3. Promote auto-qualified quarantined entities in-place:
     if a quarantined entity is now referenced by ≥2 distinct non-quarantined
     events, flip its `quarantined` flag to false and write entities.json.
  4. For every pair of events sharing ≥1 live entity:
       raw_weight = sum(1 / log(1 + degree(e))) over shared entities
     where degree(e) = number of events containing entity e.
     Rare entities contribute more than hub entities (CIA, JFK).
  5. Per-event hub cap (UNION semantics per OV-8): keep the top-3 rarest
     edges from each endpoint's perspective. An edge survives if it is in
     EITHER endpoint's top-3 list.
  6. Prune edges with weight < 0.05 (hub-only noise).
  7. Emit adjacency list: { "<event_id>": [{ "to", "weight",
     "via_entity_ids" }, ...], ... }.

Output: dist/edges.json (not committed; regenerated by GHA on every deploy).

Run: python scripts/derive_edges.py
"""
from __future__ import annotations

import json
import math
import sys
from collections import defaultdict
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent
DATA_PATH = ROOT / "data" / "data.json"
ENTITIES_PATH = ROOT / "data" / "entities.json"
DIST_DIR = ROOT / "dist"
EDGES_PATH = DIST_DIR / "edges.json"

PRUNE_THRESHOLD = 0.05
TOP_N_PER_EVENT = 3


def load_data() -> tuple[dict, list[dict]]:
    with DATA_PATH.open("r", encoding="utf-8") as f:
        data = json.load(f)
    with ENTITIES_PATH.open("r", encoding="utf-8") as f:
        entities = json.load(f)
    return data, entities


def save_entities(entities: list[dict]) -> None:
    with ENTITIES_PATH.open("w", encoding="utf-8") as f:
        json.dump(entities, f, indent=2, ensure_ascii=False)
        f.write("\n")


def promote_quarantined(
    events: list[dict], entities: list[dict]
) -> tuple[list[dict], int]:
    """
    If a quarantined entity is now referenced by ≥2 distinct events, flip
    its flag. Returns the mutated list + count of promotions. Writes
    entities.json in-place only if promotions occurred.
    """
    qid_index = {e["id"]: e for e in entities if e.get("quarantined")}
    if not qid_index:
        return entities, 0

    ref_count: dict[str, set[str]] = defaultdict(set)
    for ev in events:
        for eid in ev.get("entities", []):
            if eid in qid_index:
                ref_count[eid].add(ev["id"])

    promotions = 0
    for eid, refs in ref_count.items():
        if len(refs) >= 2:
            qid_index[eid]["quarantined"] = False
            promotions += 1

    if promotions:
        save_entities(entities)
    return entities, promotions


def build_edges(
    events: list[dict], entities: list[dict]
) -> dict[str, list[dict]]:
    # Live entities only (quarantined ones are invisible to the graph).
    live_entity_ids = {e["id"] for e in entities if not e.get("quarantined")}

    # Entity → list of event ids (for degree calc + pair generation).
    entity_to_events: dict[str, list[str]] = defaultdict(list)
    event_to_entities: dict[str, list[str]] = {}
    for ev in events:
        eid = ev["id"]
        ents = [e for e in ev.get("entities", []) if e in live_entity_ids]
        event_to_entities[eid] = ents
        for e in ents:
            entity_to_events[e].append(eid)

    # degree(e) = number of events mentioning entity e.
    degree = {e: len(evs) for e, evs in entity_to_events.items()}

    # Weight contribution per entity (rare entities = large contribution).
    def contribution(e: str) -> float:
        return 1.0 / math.log(1.0 + degree[e])

    # Generate all candidate event pairs sharing ≥1 live entity, with
    # summed contribution weight and the via-entity list. Iterate per
    # entity to avoid O(E²) over events.
    pair_weight: dict[tuple[str, str], float] = defaultdict(float)
    pair_via: dict[tuple[str, str], list[str]] = defaultdict(list)

    for entity_id, ev_list in entity_to_events.items():
        if len(ev_list) < 2:
            continue
        c = contribution(entity_id)
        # All unordered pairs of events sharing this entity.
        for i in range(len(ev_list)):
            for j in range(i + 1, len(ev_list)):
                a, b = sorted([ev_list[i], ev_list[j]])
                pair_weight[(a, b)] += c
                pair_via[(a, b)].append(entity_id)

    # Per-event top-N (UNION): for each event, rank its edges by weight,
    # keep top N; an edge survives if present in EITHER endpoint's top-N.
    per_event_edges: dict[str, list[tuple[str, str]]] = defaultdict(list)
    for (a, b), w in pair_weight.items():
        per_event_edges[a].append((b, w, (a, b)))  # type: ignore[arg-type]
        per_event_edges[b].append((a, w, (a, b)))  # type: ignore[arg-type]

    keep_set: set[tuple[str, str]] = set()
    for ev_id, edges in per_event_edges.items():
        # Sort by weight descending; highest weight = strongest (rarest)
        # contribution per the formula.
        edges.sort(key=lambda t: -t[1])
        for _, _, pair in edges[:TOP_N_PER_EVENT]:
            keep_set.add(pair)

    # Apply weight prune after the cap — cap determines membership, prune
    # drops the weakest survivors so only meaningful links remain.
    adjacency: dict[str, list[dict]] = defaultdict(list)
    for pair in keep_set:
        w = pair_weight[pair]
        if w < PRUNE_THRESHOLD:
            continue
        a, b = pair
        via = sorted(set(pair_via[pair]))
        # Graph edge weight semantics per plan: LOWER weight = STRONGER edge
        # (Dijkstra shortest-path treats weight as cost). Invert contribution.
        edge_cost = 1.0 / w
        adjacency[a].append(
            {"to": b, "weight": round(edge_cost, 4), "via_entity_ids": via}
        )
        adjacency[b].append(
            {"to": a, "weight": round(edge_cost, 4), "via_entity_ids": via}
        )

    # Deterministic ordering: neighbors sorted by weight asc, then id asc.
    for a in adjacency:
        adjacency[a].sort(key=lambda e: (e["weight"], e["to"]))

    # Emit every event id as a key, even if it has zero edges (prevents
    # KeyError in graph.js on isolated events).
    full: dict[str, list[dict]] = {ev["id"]: [] for ev in events}
    for k, v in adjacency.items():
        full[k] = v

    return full


def main() -> int:
    data, entities = load_data()
    events = data["events"]

    # Validate entity references.
    entity_ids = {e["id"] for e in entities}
    orphans: list[tuple[str, str]] = []
    for ev in events:
        for eid in ev.get("entities", []):
            if eid not in entity_ids:
                orphans.append((ev["id"], eid))
    if orphans:
        for event_id, entity_id in orphans:
            print(
                f"[WARN] event {event_id!r} references unknown entity "
                f"{entity_id!r} — skipping this reference.",
                file=sys.stderr,
            )
        # Non-fatal: filter orphans out and continue.
        for ev in events:
            ev["entities"] = [
                e for e in ev.get("entities", []) if e in entity_ids
            ]

    _, promoted = promote_quarantined(events, entities)
    if promoted:
        print(f"[+] quarantine promotions: {promoted}")

    adjacency = build_edges(events, entities)

    DIST_DIR.mkdir(parents=True, exist_ok=True)
    with EDGES_PATH.open("w", encoding="utf-8") as f:
        json.dump(adjacency, f, indent=2, ensure_ascii=False)
        f.write("\n")

    total_edges = sum(len(v) for v in adjacency.values()) // 2
    connected = sum(1 for v in adjacency.values() if v)
    print(f"[+] events:      {len(events)}")
    print(f"[+] entities:    {len(entities)} (live: "
          f"{sum(1 for e in entities if not e.get('quarantined'))})")
    print(f"[+] edges:       {total_edges}")
    print(f"[+] connected:   {connected}/{len(events)} events")
    print(f"[+] wrote {EDGES_PATH}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
